### ISSUE TITLE
CSP friendly components

### ISSUE THREAD

**Issue by Shadowfaxenator** [axzilla/templui#13]
Could you please refactor alpine js to be complient with csp policy? No inline js possible (you can extract to standalone data functions) and use csp alpine version.

**Comment by axzilla** [comment]
Thanks for bringing this up - this is a very important point regarding security and CSP compliance!

I plan to implement this right after finishing the toast component I'm currently working on:

- Switch to the Alpine.js CSP version
- Extract inline JavaScript to script tags within the .templ components using templ.OnceHandle
- Ensure proper scoping of component functionality

I'm choosing this approach to keep things simple and user-friendly. Moving JavaScript to separate files would make the components more complex to use, both for package imports and especially for copy/paste scenarios.

Do you see any concerns with this approach? Would love to hear your thoughts!

**Comment by Shadowfaxenator** [comment]
This is ok but with this approach you need to provide a nonce parameter to each component or in a context

**Comment by axzilla** [comment]
Okay, this is new territory for me. Sounds complicated, but I'll look into it later today! Do you have any better ideas?

**Comment by axzilla** [comment]
Completed in PR #16

**Comment by axzilla** [comment]
Completed in PR #16
