### ISSUE TITLE
Regarding value of checkbox

### ISSUE THREAD

**Issue by RimJur** [axzilla/templui#26]
I'm currently in the exploration of this library, everything looks so great!

I would just like to point out one small thing. Currently in [pkg/components/checkbox.templ](https://github.com/axzilla/templui/blob/main/pkg/components/checkbox.templ) when not specifying Value in `CheckboxProps`, form submission is misleading. 

I think that it would be better if value would be checked for default value and if so, would not be render as `value={ props.Value }`, because in form submission this leads to that checkbox **always** having an empty string value.

For the default browser behavior, we would need to always specify `CheckboxProps{Value: "on"}`.

Will be waiting for your opinion!

**Comment by axzilla** [comment]
Thanks for that,

You're right. I guess this is a simple fix: 0d755b0f32282d5bb8fb2c2de6bd53686bdaf623
